#!/bin/bash

#CMD="cd /mnt/FDEV/ANGULAR/workspacein28minutes"
#CMD="cd /mnt/FDEV/JHIPSTER/workspacefullstackV05/"
#CMD="cd /mnt/FDEV/JHIPSTER/workspacejhipster02/kiejhipsterhelloworld02-web"
#CMD="cd /mnt/FDEV/DROOLSWORKSPACE/workspace_kieandjhipster/"
#CMD="cd /mnt/FDEV/SPRING/CORONAVIRUS"
#CMD="cd /mnt/FDEV/SPRING/SPRINGSECURITY/workspacebaeldung/springsecurity_stepbystep"
#CMD="cd /mnt/FDEV/SPRING/SPRINGSECURITY/workspacebaeldung/springsecurity_stepbystep08_storing_password"
CMD="cd /mnt/FDEV/SPRING/SPRINGSECURITY/workspacespringbootsecurity02/springsecurity_04_setup_spring_boot_project"


echo .
echo "$CMD"
echo .
echo pwd
echo .

$CMD 

pwd
