#!/bin/bash

echo .
echo . Example:
echo .      fstr getAudioFiles *.java - Look for getAudioFiles in all java subdirectory files.
echo .      fstr getAudioFiles - Look for getAudioFiles in all subdirectory files.
echo .

if [[ $# -eq 1 ]] ; then
  CMD="grep -ir "$1" ."
fi

if [[ $# -eq 2 ]] ; then
  CMD="grep -ir "$1" --include=$2 ."
fi

echo .
echo $CMD
echo .


$CMD

