#!/bin/bash

clear

#CMD="mvn clean spring-boot:run -DskipTests=true"
CMD="mvn clean spring-boot:run -Dmaven.test.skip=true"
DBG="-Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Xrunjdwp"

if [ "$1" == "-d" ]; then
    CMD="mvnDebug spring-boot:run -DskipTests=true"
fi

echo .
echo ". Pass -d to debug"
echo .
echo "$CMD"
echo .

$CMD

