#!/bin/bash
JAVA_HOME=/mnt/FBIN/java-1.7.0
PATH=$JAVA_HOME/bin:$PATH:.
CLASSPATH=$JAVA_HOME/jre/lib/rt.jar;
#----
export JAVA_HOME
export CLASSPATH
export PATH
#----
clear
echo .
echo CLASSPATH=$CLASSPATH
echo .
echo JAVA_HOME=$JAVA_HOME
echo .
echo PATH=$PATH
echo .

ANT_HOME=/mnt/FBIN/apache-ant-1.8.2
PATH=$ANT_HOME/bin:$PATH:.
#----
export ANT_HOME
export PATH
#----
echo .
echo ANT_HOME=$ANT_HOME
echo .
echo PATH=$PATH
echo .


