#!/bin/bash
JAVA_HOME=/mnt/FBIN/jdk8
PATH=./:$JAVA_HOME/bin/:/home/pchauvet/.local/bin:/home/pchauvet/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/mnt/FBIN/bin:/home/pchauvet/.local/bin:/home/pchauvet/bin:$PATH

CLASSPATH=$JAVA_HOME/jre/lib/rt.jar;
#----
export JAVA_HOME
export CLASSPATH
export PATH
#----
clear
echo .
echo CLASSPATH=$CLASSPATH
echo .
echo JAVA_HOME=$JAVA_HOME
echo .
echo PATH=$PATH
echo .



