#!/bin/bash
JAVA_HOME=/run/media/pchauvet/FBIN/jdk-11.0.2
PATH=$JAVA_HOME/bin:$PATH:.
CLASSPATH=$JAVA_HOME/jre/lib/rt.jar;
#----
export JAVA_HOME
export CLASSPATH
export PATH
#----
clear
echo .
echo CLASSPATH=$CLASSPATH
echo .
echo JAVA_HOME=$JAVA_HOME
echo .
echo PATH=$PATH
echo .



