#!/bin/bash

MAVEN_HOME=/run/media/pchauvet/FBIN/apache-maven-3.5.2-bin
M2_HOME=$MAVEN_HOME
PATH=.:$MAVEN_HOME/bin:$PATH

#----
export MAVEN_HOME
export M2_HOME
export PATH
#----
clear
echo .
echo .
echo MAVEN_HOME=$MAVEN_HOME
echo M2_HOME=$M2_HOME
echo PATH=$PATH
echo .
echo .

